// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dashboard/jobs": {
            "get": {
                "description": "Returns the last 100 processed transfer jobs with their status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Get recent transfer jobs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_delivery_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/dashboard/queue-stats": {
            "get": {
                "description": "Returns current transfer worker queue statistics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Get queue statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_delivery_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Login user with phone number and pin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_domain_usecase.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_delivery_http_response.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_delivery_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/pay": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deduct balance from current user for payment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Make a payment",
                "parameters": [
                    {
                        "description": "Payment request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_domain_usecase.PaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_delivery_http_response.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_delivery_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/profile": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update current user's first name, last name, or address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user profile",
                "parameters": [
                    {
                        "description": "Update profile request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_domain_usecase.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_delivery_http_response.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_delivery_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Register a new user with first name, last name, phone number, address, and pin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Register request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_domain_usecase.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_delivery_http_response.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_delivery_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/topup": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Add balance to current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Top up balance",
                "parameters": [
                    {
                        "description": "Top up request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_domain_usecase.TopUpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_delivery_http_response.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_delivery_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/transactions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all transactions for current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get transaction history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_delivery_http_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/transfer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Transfer balance from current user to another user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Transfer balance",
                "parameters": [
                    {
                        "description": "Transfer request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_domain_usecase.TransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_delivery_http_response.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/mnc-fullstack-technical-test_tahap-2_internal_delivery_http_response.JSONResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "mnc-fullstack-technical-test_tahap-2_internal_delivery_http_response.JSONResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {},
                "status": {
                    "type": "string"
                }
            }
        },
        "mnc-fullstack-technical-test_tahap-2_internal_domain_usecase.LoginRequest": {
            "type": "object",
            "required": [
                "phone_number",
                "pin"
            ],
            "properties": {
                "phone_number": {
                    "type": "string"
                },
                "pin": {
                    "type": "string"
                }
            }
        },
        "mnc-fullstack-technical-test_tahap-2_internal_domain_usecase.PaymentRequest": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "remarks": {
                    "type": "string"
                }
            }
        },
        "mnc-fullstack-technical-test_tahap-2_internal_domain_usecase.RegisterRequest": {
            "type": "object",
            "required": [
                "address",
                "first_name",
                "last_name",
                "phone_number",
                "pin"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "pin": {
                    "type": "string"
                }
            }
        },
        "mnc-fullstack-technical-test_tahap-2_internal_domain_usecase.TopUpRequest": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                }
            }
        },
        "mnc-fullstack-technical-test_tahap-2_internal_domain_usecase.TransferRequest": {
            "type": "object",
            "required": [
                "amount",
                "target_user"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "remarks": {
                    "type": "string"
                },
                "target_user": {
                    "type": "string"
                }
            }
        },
        "mnc-fullstack-technical-test_tahap-2_internal_domain_usecase.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter the token with the ` + "`" + `Bearer ` + "`" + ` prefix. Example: \"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MNC Fullstack Technical Test API",
	Description:      "This is a sample e-wallet API for MNC technical test.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
